/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Pagamento;
import io.swagger.model.Transacao;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-18T22:15:48.455Z")

@Api(value = "pagamentos", description = "the pagamentos API")
@RequestMapping(value = "/fj36-payfast/v1")
public interface PagamentosApi {

    @ApiOperation(value = "Cancela um pagamento", nickname = "pagamentosIdDelete", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Pagamento cancelado") })
    @RequestMapping(value = "/pagamentos/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> pagamentosIdDelete(@ApiParam(value = "id do pagamento",required=true) @PathVariable("id") Integer id);


    @ApiOperation(value = "Confirma um pagamento", nickname = "pagamentosIdPut", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Pagamento confirmado") })
    @RequestMapping(value = "/pagamentos/{id}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> pagamentosIdPut(@ApiParam(value = "id do pagamento",required=true) @PathVariable("id") Integer id);


    @ApiOperation(value = "Cria novo pagamento", nickname = "pagamentosPost", notes = "", response = Pagamento.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Novo pagamento criado", response = Pagamento.class) })
    @RequestMapping(value = "/pagamentos",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Pagamento> pagamentosPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Transacao transacao);

}
